### ISSUE TITLE
Default seats nfcast

### ISSUE THREAD

**Issue by TanguyBarthelemy** [rjdemetra/rjd3tramoseats#3]
_Issue from @AQLT palatej/rjd3tramoseats#4_

By default the nfcast parameter of seats seems equal to -2 (same value importing a workspace with the default specification where it should be equal to -1?)

```r
library("rjd3tramoseats")
spec_tramoseats()$seats$nfcasts
#> [1] -2
```

**Comment by palatej** [comment]
I put that value by default on the request of some users. The number of forecasts as no impact on the results (Burman computes the needed number of forecasts, which depends on the model and Kalman doesn't use forecasts at all).
